export const BREEDS_BY_SPECIES = {
  DOG: [
    'Mixed Breed',
    'Labrador Retriever',
    'German Shepherd',
    'Golden Retriever',
    'French Bulldog',
    'Bulldog',
    'Poodle',
    'Beagle',
    'Rottweiler',
    'Yorkshire Terrier',
    'Boxer',
    'Dachshund',
    'Siberian Husky',
    'Doberman',
    'Great Dane',
    'Shih Tzu',
    'Border Collie',
    'Chihuahua',
    'Pomeranian',
    'Australian Shepherd',
    'Cocker Spaniel',
    'Maltese',
    'Jack Russell Terrier',
    'Cavalier King Charles Spaniel',
    'Bernese Mountain Dog',
  ],
  CAT: [
    'Mixed Breed',
    'Persian',
    'Maine Coon',
    'Ragdoll',
    'British Shorthair',
    'Siamese',
    'Bengal',
    'Abyssinian',
    'Scottish Fold',
    'Sphynx',
    'Russian Blue',
    'Norwegian Forest Cat',
    'Birman',
    'Oriental Shorthair',
    'Devon Rex',
    'Burmese',
    'Exotic Shorthair',
    'Siberian',
    'Tonkinese',
    'American Shorthair',
  ],
  BIRD: [
    'Parakeet/Budgie',
    'Cockatiel',
    'Canary',
    'Lovebird',
    'African Grey Parrot',
    'Cockatoo',
    'Macaw',
    'Finch',
    'Conure',
    'Amazon Parrot',
  ],
  RABBIT: [
    'Mixed Breed',
    'Holland Lop',
    'Mini Rex',
    'Netherland Dwarf',
    'Lionhead',
    'Flemish Giant',
    'Mini Lop',
    'Dutch',
    'Rex',
    'English Lop',
  ],
  HAMSTER: [
    'Syrian (Golden)',
    'Dwarf Campbell Russian',
    'Dwarf Winter White Russian',
    'Roborovski',
    'Chinese',
  ],
  GUINEA_PIG: [
    'American',
    'Abyssinian',
    'Peruvian',
    'Silkie',
    'Teddy',
    'Texel',
    'White Crested',
  ],
  REPTILE: [
    'Bearded Dragon',
    'Leopard Gecko',
    'Ball Python',
    'Corn Snake',
    'Red-Eared Slider Turtle',
    'Chameleon',
    'Blue-Tongued Skink',
    'Iguana',
  ],
  OTHER: [
    'Other',
  ],
} as const;

export type SpeciesKey = keyof typeof BREEDS_BY_SPECIES;

export function getBreedsForSpecies(species: string): readonly string[] {
  return BREEDS_BY_SPECIES[species as SpeciesKey] || BREEDS_BY_SPECIES.OTHER;
}
